# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
    port: 10001
    context-path: /

# mysql
spring:
    jmx:
        default-domain: property-server
    # 环境 dev|test|pro
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # 指定静态资源的路径
    resources:
        static-locations: classpath:/static/,classpath:/views/,file:${fileupload.filepath}

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml


# APP模块，是通过jwt认证的，如果要使用APP模块，则需要修改【加密秘钥】
jwt:
    # 加密秘钥
    secret: b65vhvpob8kw5qnuh09rihdjscja4ecw
    # token有效时长，7天，单位秒
    expire: 604800
    header: token

#小程序配置
wechat:
  miniapp:
    appid: wx3942055105d7de6f
    secret: 4fd259df2565176895bfa88bb2797291
    token:
    aesKey:
    msgDataFormat: JSON
  pay:
    appId: wx3f0b81b2a6f6ab31
    mchId: 
    mchKey: 
    subAppId:
    subMchId:
    keyPath:
    notifyUrl: https://x.com/api/wechat/pay/parseOrderNotifyResult

